name: cnattendance
description: An attendance application to manage in a organization to check in and check out with multiple functions to manupulate inside a office to record the basic functionality

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.2+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  http: ^1.2.0
  dio: ^5.1.2
  html: ^0.15.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.0.6
  flutter_easyloading: ^3.0.5
  device_info_plus: ^10.1.2
  expandable: ^5.0.1
  flutter_web_browser: ^0.17.1
  percent_indicator: ^4.0.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  toggle_switch: ^2.0.1
  dropdown_button2: ^2.3.9
  lottie: ^3.1.2
  flutter_html: ^3.0.0-alpha.3
  url_launcher: ^6.1.5
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  table_calendar: ^3.0.6
  intl: ^0.19.0
  image_picker: ^1.1.2
  network_info_plus: ^6.0.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  overlay_support: ^2.0.1
  flutter_ringtone_player: ^4.0.0+3
  hexcolor: ^3.0.1
  fl_chart: ^0.69.0
  overlay_loading_progress: ^1.0.0
  one_clock: ^2.0.1
  get: ^4.6.5
  readmore: ^3.0.0
  image_stack: ^2.1.1
  in_app_notification: ^1.1.2
  gallery_image_viewer: ^1.2.0
  flutter_typeahead: ^5.2.0
  flutter_textfield_autocomplete: ^1.0.2
  path_provider: ^2.0.15

  fluttertoast: ^8.2.1

  flutter_mentions: ^2.0.1

  file_picker:

  awesome_notifications: ^0.9.3+1

  nepali_english_calendar: ^1.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  font_awesome_flutter: ^10.1.0
  quick_actions: ^1.1.0
  nepali_date_picker: ^6.0.1
  focus_detector: ^2.0.1
  auto_size_text_field: ^2.2.4
  text_sizer_plus: ^1.0.5
  qr_bar_code_scanner_dialog: ^0.0.5
  nfc_manager: ^3.5.0
  http_interceptor_plus: ^0.0.1
  cloud_firestore: ^5.6.2
  uuid: ^4.3.3
  flutter_native_html_to_pdf: ^1.0.1
  share_plus: ^10.1.3
  cached_network_image: ^3.4.1
  get_storage: ^2.1.1
  flutter_translate: ^4.1.0
  flutter_displaymode: ^0.6.0
  ripple_wave: ^0.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon_ios.png"
  adaptive_icon_background: "#026CB7"
  adaptive_icon_foreground: "assets/icons/launcher_icon.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/google_sans.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/sound/
    - assets/ca/
    - assets/raw/
    - assets/i18n/
